name: api-messages
channels:
 - default
 - conda-forge
dependencies:
 - python==3.6
 - boto3==1.9.168
 - falcon==2.0.0
 - pandas==0.24.0
 - numpy==1.16.4
 - waitress==1.3.0
 - gunicorn==19.9.0
 - psycopg2==2.7.5
 - pytest==4.6.3

